/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        secondary: '#47607e',
        surface: '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-dim': '#cfdaf6',
        'surface-container': '#e8edff',
        'surface-container-low': '#f1f3ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e0e8ff',
        'surface-container-highest': '#d7e2ff',
        'surface-variant': '#d7e2ff',
        'surface-tint': '#545e76',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-surface': '#101b30',
        'on-surface-variant': '#44474c',
        'on-primary-container': '#79849d',
        'primary-container': '#101b30',
        'secondary-container': '#c2dcff',
        'on-secondary-container': '#48617e',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#bbc6e2',
        'on-primary-fixed': '#101b30',
        'on-primary-fixed-variant': '#3c475d',
        'secondary-fixed': '#d1e4ff',
        'secondary-fixed-dim': '#afc9ea',
        'on-secondary-fixed': '#001d36',
        'on-secondary-fixed-variant': '#2f4865',
        outline: '#74777d',
        'outline-variant': '#c4c6cc',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f9f9ff',
        'on-background': '#101b30',
        'inverse-surface': '#263046',
        'inverse-on-surface': '#edf0ff',
        'inverse-primary': '#bbc6e2',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Lexend', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
